Repository haru-speak/haruSpeak_iOS, pull requests merged in 2023-01, with the labels that each got.

#46 Fix: "Fixed button color to blue"
  haruSpeak_iOS.xcworkspace/xcuserdata/077tech.xcuserdatad/UserInterfaceState.xcuserstate
  haruSpeak_iOS/Resource/Assets.xcassets/Images/alarm.blue.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/alarm.blue.imageset/Vector (42).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/alarm.blue.imageset/Vector (43).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/alarm.blue.imageset/Vector (44).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/comment.unfill.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/comment.unfill.imageset/Group 184 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/comment.unfill.imageset/Group 184 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/comment.unfill.imageset/Group 184.png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/pause.blue.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/pause.blue.imageset/pause-mini-fill 1 (3).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/pause.blue.imageset/pause-mini-fill 1 (4).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/pause.blue.imageset/pause-mini-fill 1 (5).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/play.white.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/play.white.imageset/Vector (48).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/play.white.imageset/Vector (49).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/play.white.imageset/Vector (50).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.blue.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.blue.imageset/Vector (45).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.blue.imageset/Vector (46).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.blue.imageset/Vector (47).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.imageset/Group 186 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.imageset/Group 186 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/thumbsup.imageset/Group 186.png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/x.white.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/x.white.imageset/close-line 2 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/x.white.imageset/close-line 2 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/x.white.imageset/close-line 2.png
  haruSpeak_iOS/View/Home/RecordCell.swift
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
  haruSpeak_iOS/ViewController/Home/PlaylistViewController.swift
Labels: 🆕enhancement🆕

#47 test commit
  haruSpeak_iOS.xcworkspace/xcuserdata/077tech.xcuserdatad/UserInterfaceState.xcuserstate
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
Labels: 🆕enhancement🆕

#49 Feat: "Add Calendar Stretch Function Added" TEMP
  haruSpeak_iOS.xcworkspace/xcuserdata/077tech.xcuserdatad/UserInterfaceState.xcuserstate
  haruSpeak_iOS/View/Home/RecordCell.swift
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
Labels: 🆕enhancement🆕

#51 Feat: "Add Blueplaylist with action"
  haruSpeak_iOS.xcworkspace/xcuserdata/077tech.xcuserdatad/UserInterfaceState.xcuserstate
  haruSpeak_iOS/View/Home/RecordCell.swift
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
Labels: 🆕enhancement🆕

#67 Feat: RecordViewController button actions
  haruSpeak_iOS/Resource/Assets.xcassets/Images/continueRecording.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/continueRecording.imageset/Ellipse 34 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/continueRecording.imageset/Ellipse 34 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/continueRecording.imageset/Ellipse 34.png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/continueRecording.imageset/Group 222 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/continueRecording.imageset/Group 222 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/continueRecording.imageset/Group 222.png
  haruSpeak_iOS/ViewController/Record/RecordViewController.swift
  haruSpeak_iOS/ViewController/Record/SaveViewController.swift
Labels: 🆕enhancement🆕

#72 Feat: "Add playlist view"
  haruSpeak_iOS.xcodeproj/project.pbxproj
  haruSpeak_iOS/View/Home/CommentCell.swift
  haruSpeak_iOS/ViewController/Home/PlaylistViewController.swift
Labels: 🆕enhancement🆕

#73 Feat: "Add Button Action in Top View"
  haruSpeak_iOS/View/Home/CommentCell.swift
  haruSpeak_iOS/ViewController/Home/PlaylistViewController.swift
Labels: 🆕enhancement🆕

#79 Feat: "Fix Calendar in HomeViewController"
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarleft.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarleft.imageset/Vector 9 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarleft.imageset/Vector 9 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarleft.imageset/Vector 9.png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarright.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarright.imageset/Vector 8 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarright.imageset/Vector 8 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/calendarright.imageset/Vector 8.png
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
  haruSpeak_iOS/ViewController/Home/PlaylistViewController.swift
Labels: 🆕enhancement🆕

#84 Feat: "MembershipViewController 아이디 비밀번호 비밀번호 확인 형식 검사"
  haruSpeak_iOS/SceneDelegate.swift
  haruSpeak_iOS/ViewController/Authentication/EmailLoginViewController.swift
  haruSpeak_iOS/ViewController/Authentication/MembershipViewController.swift
  haruSpeak_iOS/ViewController/Record/SaveViewController.swift
Labels: 🆕enhancement🆕

#85 Feat: "DatePickerViewController"
  haruSpeak_iOS.xcodeproj/project.pbxproj
  haruSpeak_iOS/Resource/Assets.xcassets/Images/vector.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/vector.imageset/Vector 1 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/vector.imageset/Vector 1 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/vector.imageset/Vector 1.png
  haruSpeak_iOS/ViewController/Authentication/DatePickerViewController.swift
  haruSpeak_iOS/ViewController/Authentication/MembershipViewController.swift
Labels: 🆕enhancement🆕

#86 Feat: "DatePickerViewController, Send Data to MembershipVC"
  haruSpeak_iOS/SceneDelegate.swift
  haruSpeak_iOS/ViewController/Authentication/AuthenticationViewController.swift
  haruSpeak_iOS/ViewController/Authentication/DatePickerViewController.swift
  haruSpeak_iOS/ViewController/Authentication/EmailLoginViewController.swift
  haruSpeak_iOS/ViewController/Authentication/MSDoneViewController.swift
  haruSpeak_iOS/ViewController/Authentication/MembershipViewController.swift
  haruSpeak_iOS/ViewController/Record/DeleteViewController.swift
  haruSpeak_iOS/ViewController/Record/RecordViewController.swift
Labels: 🐞bug🐞, 🆕enhancement🆕

#87 Feat: "RecordViewController, TimeLabel initialize"
  haruSpeak_iOS/ViewController/Record/RecordViewController.swift
  haruSpeak_iOS/ViewController/Record/SaveViewController.swift
Labels: 🐞bug🐞

#94 Feat: "Add Second, Third, Fifth ViewController for User Setting"
  haruSpeak_iOS.xcodeproj/project.pbxproj
  haruSpeak_iOS/SceneDelegate.swift
  haruSpeak_iOS/View/UserSetting/ProgressBarView.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/FifthViewController.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/SecondGiverViewController.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/SecondLearnerViewController.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/ThirdViewController.swift
Labels: 🆕enhancement🆕

#98 Feat: "Fixed Calendar UI height"
  haruSpeak_iOS/View/Home/CustomTabbar.swift
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
Labels: 🆕enhancement🆕

#99 Feat: "Add different view when the amount of record cell is nil
  haruSpeak_iOS/View/Home/CustomTabbar.swift
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
Labels: 🆕enhancement🆕

#100 Feat: "Authentication&EmailLogin&JoinMS NSMutableAttributedString"
  haruSpeak_iOS/ViewController/Authentication/AuthenticationViewController.swift
  haruSpeak_iOS/ViewController/Authentication/EmailLoginViewController.swift
  haruSpeak_iOS/ViewController/Authentication/JoinMSViewController.swift
Labels: 🐞bug🐞

#102 Feat: "Add mymate friend collectionview"
  haruSpeak_iOS.xcodeproj/project.pbxproj
  haruSpeak_iOS/Resource/Assets.xcassets/Images/filterbutton.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/filterbutton.imageset/Vector (51).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/filterbutton.imageset/Vector (52).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/filterbutton.imageset/Vector (53).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/morefriend.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/morefriend.imageset/Group 284 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/morefriend.imageset/Group 284 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/morefriend.imageset/Group 284.png
  haruSpeak_iOS/View/Home/CustomTabbar.swift
  haruSpeak_iOS/View/Home/MyMateFriendCell.swift
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
Labels: 🆕enhancement🆕

#107 Fix: "fix bottom layout for user setting"
  Pods/Pods.xcodeproj/xcuserdata/077tech.xcuserdatad/xcschemes/xcschememanagement.plist
  haruSpeak_iOS/SceneDelegate.swift
  haruSpeak_iOS/View/Home/RecordCell.swift
  haruSpeak_iOS/ViewController/Home/HomeViewController.swift
  haruSpeak_iOS/ViewController/Home/PlaylistViewController.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/FifthViewController.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/SecondGiverViewController.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/SecondLearnerViewController.swift
  haruSpeak_iOS/ViewController/UserSettingViewController/ThirdViewController.swift
Labels: 🆕enhancement🆕

#115 Feat: "Add MyPage ViewController Functions"
  haruSpeak_iOS.xcodeproj/project.pbxproj
  haruSpeak_iOS/Info.plist
  haruSpeak_iOS/Resource/Assets.xcassets/Colors/englishTag.colorset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Colors/koreanTag.colorset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Colors/objectiveTag.colorset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/crossfollow.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/crossfollow.imageset/Ic_맞팔 중 표시 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/crossfollow.imageset/Ic_맞팔 중 표시 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/crossfollow.imageset/Ic_맞팔 중 표시.png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/ellipsis.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/ellipsis.imageset/Group 262 (1).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/ellipsis.imageset/Group 262 (2).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/ellipsis.imageset/Group 262.png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/moreprofile.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/moreprofile.imageset/Vector (63).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/moreprofile.imageset/Vector (64).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/moreprofile.imageset/Vector (65).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.fill.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.fill.imageset/Vector (66).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.fill.imageset/Vector (67).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.fill.imageset/Vector (68).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.imageset/Contents.json
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.imageset/Vector (69).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.imageset/Vector (70).png
  haruSpeak_iOS/Resource/Assets.xcassets/Images/star.imageset/Vector (71).png
  haruSpeak_iOS/Utilities/Extensions/UIColor+.swift
  haruSpeak_iOS/View/MyPage/CustomTabbarMyPage.swift
  haruSpeak_iOS/View/MyPage/FollowerCell.swift
  haruSpeak_iOS/View/MyPage/FollowingCell.swift
  haruSpeak_iOS/ViewController/MyPage/CustomTabbar.swift
  haruSpeak_iOS/ViewController/MyPage/FollowerFollowingViewController.swift
  haruSpeak_iOS/ViewController/MyPage/MyPageViewController.swift
Labels: 🆕enhancement🆕
